# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# Consul variables
consul_install = ["true", "1"].include?((ENV['CONSUL_INSTALL'] || true).to_s.downcase)
consul_host_port = ENV['CONSUL_HOST_PORT'] || 8500
consul_version = ENV['CONSUL_VERSION'] || "1.2.3"
consul_ent_url = ENV['CONSUL_ENT_URL']
consul_group = "consul"
consul_user = "consul"
consul_comment = "Consul"
consul_home = "/srv/consul"

# Vault variables
vault_host_port = ENV['VAULT_HOST_PORT'] || 8200
vault_version = ENV['VAULT_VERSION'] || "0.11.3"
vault_ent_url = ENV['VAULT_ENT_URL']
vault_group = "vault"
vault_user = "vault"
vault_comment = "Vault"
vault_home = "/srv/vault"

# Vault PKI variables
vault_pki_runner_branch = ENV['VAULT_PKI_RUNNER_BRANCH'] || 'master'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  os = "bento/ubuntu-16.04"
  net_ip = "192.168.50"

  config.vm.define :master, primary: true do |master_config|
    master_config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 1
        vb.name = "master"
    end

    master_config.vm.box = "#{os}"
    master_config.vm.host_name = 'saltmaster.local'
    master_config.vm.network "private_network", ip: "#{net_ip}.10"
    master_config.vm.synced_folder "saltstack/salt/", "/srv/salt"
    master_config.vm.synced_folder "saltstack/pillar/", "/srv/pillar"
    master_config.vm.synced_folder "../.", "/srv/formulas/vault-pki-formula"

    master_config.vm.provision :salt do |salt|
      salt.master_config = "saltstack/etc/master"
      salt.master_key = "saltstack/keys/master_minion.pem"
      salt.master_pub = "saltstack/keys/master_minion.pub"
      salt.minion_key = "saltstack/keys/master_minion.pem"
      salt.minion_pub = "saltstack/keys/master_minion.pub"
      salt.seed_master = {
                          "minion1" => "saltstack/keys/minion1.pub",
                          # "minion2" => "saltstack/keys/minion2.pub"
                         }
      salt.version = "2017.7.2"
      salt.install_type = "stable"
      salt.install_master = true
      salt.no_minion = true
      salt.verbose = true
      salt.colorize = true
      salt.bootstrap_options = "-P -c /tmp"
    end

    master_config.vm.provision :shell,
      inline: "curl https://raw.githubusercontent.com/hashicorp/guides-configuration/master/shared/scripts/base.sh | bash"

    master_config.vm.network :forwarded_port,
      guest: 8500,
      host: consul_host_port,
      auto_correct: true

    master_config.vm.provision "shell",
      inline: "curl https://raw.githubusercontent.com/hashicorp/guides-configuration/master/shared/scripts/setup-user.sh | bash",
      env: {
        "GROUP" => consul_group,
        "USER" => consul_user,
        "COMMENT" => consul_comment,
        "HOME" => consul_home,
      }
    master_config.vm.provision "shell",
      inline: "curl https://raw.githubusercontent.com/hashicorp/guides-configuration/master/consul/scripts/install-consul.sh | bash",
      env: {
        "VERSION" => consul_version,
        "URL" => consul_ent_url,
        "USER" => consul_user,
        "GROUP" => consul_group,
      }
    master_config.vm.provision "shell", inline: "curl https://raw.githubusercontent.com/hashicorp/guides-configuration/master/consul/scripts/install-consul-systemd.sh | bash"

    master_config.vm.network :forwarded_port, guest: 8200, host: vault_host_port, auto_correct: true
    master_config.vm.provision "shell", inline: "curl https://raw.githubusercontent.com/hashicorp/guides-configuration/master/shared/scripts/setup-user.sh | bash",
      env: {
        "GROUP" => vault_group,
        "USER" => vault_user,
        "COMMENT" => vault_comment,
        "HOME" => vault_home,
      }
    master_config.vm.provision "shell", inline: "curl https://raw.githubusercontent.com/hashicorp/guides-configuration/master/vault/scripts/install-vault.sh | bash",
      env: {
        "VERSION" => vault_version,
        "URL" => vault_ent_url,
        "USER" => vault_user,
        "GROUP" => vault_group,
      }
    master_config.vm.provision "shell", inline: "curl https://raw.githubusercontent.com/hashicorp/guides-configuration/master/vault/scripts/install-vault-systemd.sh | bash"

    master_config.vm.provision "shell", inline: "curl https://raw.githubusercontent.com/hashicorp/guides-configuration/master/vault/scripts/install-vault-systemd.sh | bash"

    master_config.vm.provision "shell",
      path: "script/bootstrap-vault-pki-runner.sh",
      env: {"VAULT_PKI_RUNNER_BRANCH" => vault_pki_runner_branch}

    master_config.vm.provision "shell",
      path: "script/prepare-vault-pki-saltmaster.sh"

    master_config.vm.provision "shell",
      path: "script/install-test-framework.sh"
  end

  [
    ["minion1",    "#{net_ip}.11",    "1024",    os ],
    # ["minion2",    "#{net_ip}.12",    "1024",    os ],
  ].each do |vmname,ip,mem,os|
    config.vm.define "#{vmname}" do |minion_config|
      minion_config.vm.provider "virtualbox" do |vb|
          vb.memory = "#{mem}"
          vb.cpus = 1
          vb.name = "#{vmname}"
      end

      minion_config.vm.box = "#{os}"
      minion_config.vm.hostname = "#{vmname}"
      minion_config.vm.network "private_network", ip: "#{ip}"

      minion_config.vm.provision :salt do |salt|
        salt.minion_config = "saltstack/etc/#{vmname}"
        salt.minion_key = "saltstack/keys/#{vmname}.pem"
        salt.minion_pub = "saltstack/keys/#{vmname}.pub"
        salt.version = "2017.7.2"
        salt.install_type = "stable"
        salt.verbose = true
        salt.colorize = true
        salt.bootstrap_options = "-P -c /tmp"
      end

      minion_config.vm.provision "shell",
        path: "script/prepare-salt-minion.sh"

      minion_config.vm.provision "shell",
        path: "script/install-test-framework.sh"
    end
  end
end
